fernetKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=
webserverSecretKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=

dags:
  gitSync:
    enabled: true
    repo: https://github.com/vinibeni2801/proj-data-engineering-on-k8s.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"